export interface SamplePlan {
  id: string;
  name: string;
  description: string;
  category: "antipattern" | "optimized";
  query: string;
  json: string;
}

export const SAMPLE_PLANS: SamplePlan[] = [
  {
    id: "seq_scan_filtered",
    name: "Filtered Seq Scan (95% Discarded)",
    description: "Sequential scan on orders table scans 100,000 rows and discards 95,000 via WHERE filter.",
    category: "antipattern",
    query: "SELECT * FROM orders WHERE status = 'pending' AND created_at >= '2024-01-01';",
    json: JSON.stringify(
      [
        {
          Plan: {
            "Node Type": "Seq Scan",
            "Parallel Aware": false,
            "Relation Name": "orders",
            "Schema": "public",
            "Alias": "orders",
            "Startup Cost": 0.0,
            "Total Cost": 2150.0,
            "Plan Rows": 4500,
            "Plan Width": 36,
            "Actual Startup Time": 0.022,
            "Actual Total Time": 38.45,
            "Actual Rows": 5000,
            "Actual Loops": 1,
            "Filter": "((status = 'pending'::text) AND (created_at >= '2024-01-01'::date))",
            "Rows Removed by Filter": 95000,
            "Shared Hit Blocks": 850,
            "Shared Read Blocks": 120,
          },
          "Planning Time": 0.115,
          "Execution Time": 39.12,
        },
      ],
      null,
      2
    ),
  },
  {
    id: "row_estimate_mismatch",
    name: "Planner Estimate Mismatch (10,000x)",
    description: "Planner estimated 10 rows but actual execution returned 100,000 rows due to stale statistics.",
    category: "antipattern",
    query: "SELECT * FROM events WHERE tenant_id = 't_999' AND event_type = 'page_view';",
    json: JSON.stringify(
      [
        {
          Plan: {
            "Node Type": "Seq Scan",
            "Relation Name": "events",
            "Schema": "public",
            "Alias": "events",
            "Startup Cost": 0.0,
            "Total Cost": 1420.0,
            "Plan Rows": 10,
            "Plan Width": 64,
            "Actual Startup Time": 0.035,
            "Actual Total Time": 74.5,
            "Actual Rows": 100000,
            "Actual Loops": 1,
            "Filter": "((tenant_id = 't_999'::text) AND (event_type = 'page_view'::text))",
            "Rows Removed by Filter": 500,
          },
          "Planning Time": 0.09,
          "Execution Time": 82.3,
        },
      ],
      null,
      2
    ),
  },
  {
    id: "sort_spill_to_disk",
    name: "Sort Spill to Disk (work_mem exhaustion)",
    description: "Sort operation exhausted available work_mem and spilled 14.8 MB of temporary tuples to disk.",
    category: "antipattern",
    query: "SELECT id, payload, created_at FROM logs ORDER BY payload DESC;",
    json: JSON.stringify(
      [
        {
          Plan: {
            "Node Type": "Sort",
            "Startup Cost": 8420.0,
            "Total Cost": 9150.0,
            "Plan Rows": 50000,
            "Plan Width": 128,
            "Actual Startup Time": 62.4,
            "Actual Total Time": 95.8,
            "Actual Rows": 50000,
            "Actual Loops": 1,
            "Sort Key": ["payload DESC"],
            "Sort Method": "external merge",
            "Sort Space Used": 14800,
            "Sort Space Type": "Disk",
            "Plans": [
              {
                "Node Type": "Seq Scan",
                "Relation Name": "logs",
                "Schema": "public",
                "Alias": "logs",
                "Startup Cost": 0.0,
                "Total Cost": 3120.0,
                "Plan Rows": 50000,
                "Plan Width": 128,
                "Actual Startup Time": 0.04,
                "Actual Total Time": 18.2,
                "Actual Rows": 50000,
                "Actual Loops": 1,
              },
            ],
          },
          "Planning Time": 0.18,
          "Execution Time": 98.4,
        },
      ],
      null,
      2
    ),
  },
  {
    id: "hash_multiple_batches",
    name: "Multi-Batch Hash Join (4 Batches)",
    description: "Hash join exceeded work_mem and required 4 on-disk partition batches.",
    category: "antipattern",
    query: "SELECT c.id, c.name, o.total FROM customers c JOIN orders o ON c.id = o.customer_id;",
    json: JSON.stringify(
      [
        {
          Plan: {
            "Node Type": "Hash Join",
            "Join Type": "Inner",
            "Startup Cost": 1200.0,
            "Total Cost": 6500.0,
            "Plan Rows": 40000,
            "Plan Width": 48,
            "Actual Startup Time": 14.2,
            "Actual Total Time": 88.6,
            "Actual Rows": 40000,
            "Actual Loops": 1,
            "Hash Cond": "(o.customer_id = c.id)",
            "Plans": [
              {
                "Node Type": "Seq Scan",
                "Relation Name": "orders",
                "Alias": "o",
                "Startup Cost": 0.0,
                "Total Cost": 2500.0,
                "Plan Rows": 40000,
                "Plan Width": 24,
                "Actual Startup Time": 0.03,
                "Actual Total Time": 15.1,
                "Actual Rows": 40000,
                "Actual Loops": 1,
              },
              {
                "Node Type": "Hash",
                "Startup Cost": 800.0,
                "Total Cost": 800.0,
                "Plan Rows": 20000,
                "Plan Width": 32,
                "Actual Startup Time": 14.1,
                "Actual Total Time": 14.1,
                "Actual Rows": 20000,
                "Actual Loops": 1,
                "Hash Batches": 4,
                "Hash Buckets": 8192,
                "Original Hash Batches": 1,
                "Peak Memory Usage": 4096,
                "Plans": [
                  {
                    "Node Type": "Seq Scan",
                    "Relation Name": "customers",
                    "Alias": "c",
                    "Startup Cost": 0.0,
                    "Total Cost": 800.0,
                    "Plan Rows": 20000,
                    "Plan Width": 32,
                    "Actual Startup Time": 0.02,
                    "Actual Total Time": 7.3,
                    "Actual Rows": 20000,
                    "Actual Loops": 1,
                  },
                ],
              },
            ],
          },
          "Planning Time": 0.25,
          "Execution Time": 92.1,
        },
      ],
      null,
      2
    ),
  },
  {
    id: "nested_loop_heavy",
    name: "Heavy Nested Loop (5,000 Loops)",
    description: "Nested Loop join executed 5,000 inner loops taking 82% of total execution time.",
    category: "antipattern",
    query: "SELECT * FROM users u JOIN activity_logs a ON u.id = a.user_id WHERE u.is_active = true;",
    json: JSON.stringify(
      [
        {
          Plan: {
            "Node Type": "Nested Loop",
            "Join Type": "Inner",
            "Startup Cost": 0.42,
            "Total Cost": 9840.0,
            "Plan Rows": 5000,
            "Plan Width": 80,
            "Actual Startup Time": 0.08,
            "Actual Total Time": 115.4,
            "Actual Rows": 5000,
            "Actual Loops": 1,
            "Plans": [
              {
                "Node Type": "Seq Scan",
                "Relation Name": "users",
                "Alias": "u",
                "Startup Cost": 0.0,
                "Total Cost": 120.0,
                "Plan Rows": 5000,
                "Plan Width": 40,
                "Actual Startup Time": 0.02,
                "Actual Total Time": 2.1,
                "Actual Rows": 5000,
                "Actual Loops": 1,
                "Filter": "(is_active = true)",
              },
              {
                "Node Type": "Index Scan",
                "Relation Name": "activity_logs",
                "Alias": "a",
                "Startup Cost": 0.42,
                "Total Cost": 1.94,
                "Plan Rows": 1,
                "Plan Width": 40,
                "Actual Startup Time": 0.018,
                "Actual Total Time": 0.021,
                "Actual Rows": 1,
                "Actual Loops": 5000,
                "Index Cond": "(user_id = u.id)",
              },
            ],
          },
          "Planning Time": 0.32,
          "Execution Time": 118.2,
        },
      ],
      null,
      2
    ),
  },
  {
    id: "filter_after_index_scan",
    name: "Inefficient Index Scan (85% Discarded Post-Index)",
    description: "Index scan uses single-column index on 'status', then discards 85,000 rows on secondary 'region' filter.",
    category: "antipattern",
    query: "SELECT * FROM shipments WHERE status = 'in_transit' AND destination_region = 'EU-WEST';",
    json: JSON.stringify(
      [
        {
          Plan: {
            "Node Type": "Index Scan",
            "Relation Name": "shipments",
            "Schema": "public",
            "Alias": "shipments",
            "Index Name": "idx_shipments_status",
            "Startup Cost": 0.42,
            "Total Cost": 3120.0,
            "Plan Rows": 15000,
            "Plan Width": 64,
            "Actual Startup Time": 0.05,
            "Actual Total Time": 45.2,
            "Actual Rows": 15000,
            "Actual Loops": 1,
            "Index Cond": "(status = 'in_transit'::text)",
            "Filter": "(destination_region = 'EU-WEST'::text)",
            "Rows Removed by Filter": 85000,
          },
          "Planning Time": 0.14,
          "Execution Time": 46.8,
        },
      ],
      null,
      2
    ),
  },
  {
    id: "optimized_index_scan",
    name: "Clean Query (Zero Anti-Patterns)",
    description: "Fully covered Index Only Scan executing in under 0.5 milliseconds with zero buffer spills.",
    category: "optimized",
    query: "SELECT id, user_id FROM orders WHERE user_id = 4210 ORDER BY id DESC LIMIT 20;",
    json: JSON.stringify(
      [
        {
          Plan: {
            "Node Type": "Limit",
            "Startup Cost": 0.42,
            "Total Cost": 1.15,
            "Plan Rows": 20,
            "Plan Width": 16,
            "Actual Startup Time": 0.035,
            "Actual Total Time": 0.28,
            "Actual Rows": 20,
            "Actual Loops": 1,
            "Plans": [
              {
                "Node Type": "Index Only Scan",
                "Relation Name": "orders",
                "Index Name": "idx_orders_user_id_id",
                "Startup Cost": 0.42,
                "Total Cost": 14.8,
                "Plan Rows": 350,
                "Plan Width": 16,
                "Actual Startup Time": 0.034,
                "Actual Total Time": 0.26,
                "Actual Rows": 20,
                "Actual Loops": 1,
                "Index Cond": "(user_id = 4210)",
                "Heap Fetches": 0,
                "Shared Hit Blocks": 4,
              },
            ],
          },
          "Planning Time": 0.08,
          "Execution Time": 0.35,
        },
      ],
      null,
      2
    ),
  },
];
